### ISSUE TITLE
01 Sorting/ Implement Bubble Sort

### ISSUE THREAD

**Issue by FazeelUsmani** [FazeelUsmani/GeeksForGeeks-DSA-2#13]
**Implement Bubble Sort**

The task is to complete bubble() function which is used to implement Bubble Sort!

Example 1:

Input: 
5
4 1 3 9 7

Output: 
1 3 4 7 9
Example 2:

Input:
10 
10 9 8 7 6 5 4 3 2 1

Output: 
1 2 3 4 5 6 7 8 9 10

Your Task: This is a function problem. You only need to complete the function bubble() that sorts the array. Printing is done automatically by the driver code.

Expected Time Complexity: O(N).
Expected Auxiliary Space: O(1).

Constraints:
1 <= N <= 103
1 <= arr[i] <= 103

**Comment by nisthajnn** [comment]
Please assign to me
