### ISSUE TITLE
Implement Max Circular Subarray Sum [problem no 19]

### ISSUE THREAD

**Issue by FazeelUsmani** [FazeelUsmani/GeeksForGeeks-DSA-2#3]
Given an array arr[] of N integers arranged in a circular fashion. Your task is to find the maximum contiguous subarray sum.

Example 1:

Input:
N = 7
arr[] = {8,-8,9,-9,10,-11,12}
Output: 22
Explanation:  Starting from the last 
element of the array, i.e, 12, and 
moving in a circular fashion, we 
have max subarray as 12, 8, -8, 9, 
-9, 10, which gives maximum sum 
as 22.
Example 2:

Input:
N = 8
arr[] = {10,-3,-4,7,6,5,-4,-1}
Output: 23
Explanation: Sum of the circular 
subarray with maximum sum is 23
Your Task:
The task is to complete the function circularSubarraySum() which returns a sum of the circular subarray with maximum sum.

Expected Time Complexity: O(N).
Expected Auxiliary Space: O(1).

Constraints:
1 <= N <= 106
-106 <= Arr[i] <= 106

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by FazeelUsmani** [comment]
Hi, @chiillax. Can you describe your approach? 

Anyways, you need to run 2 variations of Kadane here, first the normal max subarray and the (total - min subarray) and pic the max among them.

**Comment by chiillax** [comment]
Please review #5

**Comment by FazeelUsmani** [comment]
Accepted!!
